### ISSUE TITLE
Error while running python3 scope_start.py --config-file radio_interactive.conf

### ISSUE THREAD

**Issue by mrkouchaki** [wineslab/colosseum-scope#1]
Hi I attached screenshot of the error I got while implementing python3 scope_start.py --config-file radio_interactive.conf.

It seems there should be built a run.log file in /logs/ directory but there is not any .log file
![Screenshot from 2022-06-11 19-06-35](https://user-images.githubusercontent.com/93693562/173208892-27216094-78c8-4e2c-bd0f-2c5b1f00415d.png)
,

**Comment by leonardobonati** [comment]
Hi, please make sure that the `/logs` directory exists on your machine, and that your user can write inside it.

As an alternative, you can change the default directory where logs are saved https://github.com/wineslab/colosseum-scope/blob/b7176a5c334ffbb9f3bbeb61a6e805c58649fddb/radio_api/scope_start.py#L662

**Comment by mrkouchaki** [comment]
I checked, there is not any /logs directory, I think you mean I should built it manually, just would you please tell me where it should be exactly? if it should be at :
/colosseum-scope/radio_api/ ? 
or
/usr/lib/python3.8/logging/ ?

**Comment by leonardobonati** [comment]
If you wish to maintain the default directory, the absolute path should be `/logs` at the root level of your system.

**Comment by mrkouchaki** [comment]
Thanks, also got an error on "scope_start.py", line 694. I changed the path and it is working.
