### ISSUE TITLE
question about function set_slice_resources(slice_idx: int, slice_mask: str)

### ISSUE THREAD

**Issue by hanghoo** [wineslab/colosseum-scope#10]
Hello,

I was wondering if the function set_slice_resources() can be used to assign specific PRBs (index) based on channel conditions for different slices. 

In addition, I read the paper "Intelligence and Learning in O-RAN for Data-Driven NextG Cellular Networks". It looks like this type of resource scheduling does not support at the DU. What do you think of it?

**Comment by leonardobonati** [comment]
Hello,

At this time, and without introducing further modifications to the code, you can only allow a specific slice to use or not certain RBGs.

**Comment by hanghoo** [comment]
Hi @leonardobonati,

Do the RBGs need to be specified in the _conf_ file? Thank you very much.

**Comment by leonardobonati** [comment]
Hello, you can specify them in the config file for them to be written as the initial configuration. Otherwise, you can manually set them in the `slicing_allocation_mask_tenant_X.txt` files, where `X` is the slice ID (https://github.com/wineslab/colosseum-scope/tree/main/radio_code/scope_config/slicing).

**Comment by hanghoo** [comment]
Hi @leonardobonati, 

Thanks much for your explanation. Based on this, I understand that the slicing group is a hyperparameter, not learning from Agent, right?

If this is the case, why do I see the output of _xApp sched-slicing_ PRB is dynamic instead of predefined? Thank you very much.

**Comment by leonardobonati** [comment]
Hello,

The user allocation to slices is fixed and the current code does not allow you to change it at run time. The RBGs allocated to the slice can be changed by writing them on the slicing allocation files, which are periodically reloaded at run time.
