### ISSUE TITLE
Upgrading to srsRAN 22.10

### ISSUE THREAD

**Issue by aabedii** [wineslab/colosseum-scope#6]
Is it relatively easy for someone to upgrade scope to work with the latest version of srsRAN? I appreciate some pointers.

**Comment by leonardobonati** [comment]
I would say it's rather involved as SCOPE was based on srsRAN version 20.04 (which is mainly LTE), while as far as I know 22.10 has been rewritten to implement 5G-oriented functionalities. That said, it really depends which parts you wish to extend (e.g., implementing the collection of the KPIs measured by srsRAN might be easier than programming novel schedulers or slicing functionalities from scratch).

**Comment by aabedii** [comment]
Thank you for the answer.
