### ISSUE TITLE
Metrics.csv

### ISSUE THREAD

**Issue by Adwi11** [wineslab/colosseum-scope#8]
I have been running scope sole just to test, but there is no produced metrics.csv file at runtime. Do I need to run it which some testbed in order to create that metrics file ?

**Comment by Adwi11** [comment]
Can I simulate that using scope alone? I don't see the param which enables that exchange in the set of its configurations.

**Comment by leonardobonati** [comment]
You would usually do that by running it on two different compute machines with software-defined radios connected to them. srsRAN should also let you use a simulation mode with zmq but I've never used it.

**Comment by leonardobonati** [comment]
You should be able to, provided that you set the IP addresses accordingly. About the metric generation, I've never used this in zmq mode but there is a `debug` mode to send fixed metrics from the BS to the xApp once the xApp subscribes to the BS. This might be helpful to verify connectivity. https://github.com/wineslab/colosseum-scope-e2/blob/6ba74250dec879458d35ee887d41b29e14fbb098/build_odu.sh#L6

**Comment by Adwi11** [comment]
Okay, so I think it's better to use colosseum itself to use scope and for xApp development. Could we discuss the use and access of colosseum for the same and exactly which containers I should use for getting the metrics and then using it in xApp.

**Comment by leonardobonati** [comment]
- Here's the link to ask for Colosseum access: https://docs.google.com/forms/d/e/1FAIpQLScHZ7gNyO4TB8b2xXPnbvPCSzGv22i0NREQ7p2XZyhF-dNQWA/viewform
- Here's the tutorial on SCOPE & ColO-RAN with details on which images to use: https://openrangym.com/tutorials/scope-coloran-o-ran
