### ISSUE TITLE
questions about scope_start.py

### ISSUE THREAD

**Issue by hanghoo** [wineslab/colosseum-scope#9]
Hello,

I have successfully run the SCOPE and O-RAN near-RT RIC tutorial on the Colosseum testbed. The scope-based BS and UEs both can run scope_start.py with radio_interactive.conf for iperf3 testing.
If there is needed to run different traffic based on the Traffic Generator (TGEN) with collecting metrics, where I should start? Thank you very much for your assistance!

**Comment by leonardobonati** [comment]
Hello,

To run different traffic, you can set the iPerf flag in the radio_interactive.conf to `False` and run your own traffic. To use the traffic generator you need to use commands such as `iptables` to perform SNAT/DNAT of the packets with the addresses of BS and UEs.

**Comment by hanghoo** [comment]
Hi @leonardobonati, thank you very much for your suggestions. I will look at the MGEN tool.
